### ISSUE TITLE
[Bug]: Incompatible With ViaFabric

### ISSUE THREAD

**Issue by SkeleBones** [Fuzss/forgeconfigapiport#38]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.10

### Notes (Required)

![image](https://user-images.githubusercontent.com/38815328/219878002-5eb83de6-abee-48ed-a2de-8c5ff77da047.png)

This error shows up when trying to connect to a server that is on 1.19.3 and that is using ViaFabric from a 1.19.2 client.

### latest.log (Optional)
[latest.log](https://github.com/Fuzss/forgeconfigapiport/files/10774762/latest.log)

_No response_

**Comment by SkeleBones** [comment]
Also, the creator of ViaFabric said the issue isn't on their end.

**Comment by Fuzss** [comment]
Should be fixed in v4.2.11.

**Comment by SkeleBones** [comment]
![image](https://user-images.githubusercontent.com/38815328/219895718-7787d203-47b4-4777-89d9-cbb5052a84e8.png)

Same issue is still happening. 

New Log - 
[latest.log](https://github.com/Fuzss/forgeconfigapiport/files/10775131/latest.log)

**Comment by Fuzss** [comment]
The issue seems to be unrelated to this mod then. As of v4.2.11 I‘m no longer touching any command argument types.
